### ISSUE TITLE
Add polytope cross-sections

### ISSUE THREAD

**Issue by vihdzp** [OfficialURL/miratope-rs#23]
This would slice the polytope by some hyperplane to create a polytope of one rank lower.

**Comment by galoomba1** [comment]
Currently works for polytopes without nonconvex polygon faces.

**Comment by vihdzp** [comment]
Seems to work for nonconvex polytopes too now. Closing this issue.

**Comment by vihdzp** [comment]
Galoomba kindly reminds me that this still doesn't work when slices pass through vertices and that it probably behaves weirdly in polygons. Reopening until we figure out what to do in these cases.

**Comment by vihdzp** [comment]
Actually, I'll instead close this issue and make further issues for problems that still exist with cross-sections.
