### ISSUE TITLE
Using menus closes them

### ISSUE THREAD

**Issue by gitRaiku** [OfficialURL/miratope-rs#34]
Os: ``Linux Raiku 5.11.21-hardened1-2-hardened #1 SMP PREEMPT Fri, 14 May 2021 21:06:07 +0000 x86_64 GNU/Linux``

Miratope version git hash: ``70811e1``

Problem: 

Whenever browsing through a menu it closes even if it isn't a leaf.

VIdeo: https://youtu.be/iHyF1gcDy4g

**Comment by gitRaiku** [comment]
Seems like this is a problem with [bevy](https://github.com/bevyengine/bevy) and not miratope

**Comment by vihdzp** [comment]
This is indeed a limitation of `egui`. I've proposed some ideas to solve it in this issue thread: https://github.com/emilk/egui/issues/335
