### ISSUE TITLE
Miratope can't render 17 or higher dimensional hypercubes/orthoplexes without crashing.

### ISSUE THREAD

**Issue by Minesh827** [OfficialURL/miratope-rs#44]
When I set the dimension count to 17 or higher for the hypercube or orthoplex under the generic folder and then click on the hypercube/orthoplex button to render them, it crashes. It doesn't crash like this when I set the dimension count to 17 or more (up to 20) for the simplex analogues. Is it because these hypercubes and orthoplexes have too many facets or that my storage space is full? I am using miratope version v0.0.3.
<img width="109" alt="Capture" src="https://github.com/user-attachments/assets/0ee5f382-74fd-4ab1-9f12-3a6cc659e488">

**Comment by galoomba1** [comment]
Hypercubes and orthoplexes have 3^n elements, simplices have 2^n. At those values of n, that fills up the whole RAM and crashes. Not fixable with the way Miratope stores polytopes.
